const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={templates:[],selected:'lecture',job:null,tab:'aligned',editing:false,templateEdit:null,poll:null};
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stamp=t=>{let n=Math.floor(Number(t)||0);return `${String(Math.floor(n/3600)).padStart(2,'0')}:${String(Math.floor(n/60)%60).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`};
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,4200)}
async function api(path,options={}){let r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...options.headers}});if(r.status===401){if(!$('#authDialog').open)$('#authDialog').showModal();throw Error('请先输入访问口令')}let data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:'输入不符合要求，请检查后重试');return data}
function safeUrl(url,image=false){if(image)return /^\/media\/[a-f0-9]{32}\/frames\/\d{10}\.jpg$/.test(url)?url:'';try{let u=new URL(url,location.origin);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return ''}}
function inline(text){let escaped=escape(text);const tokens=[];escaped=escaped.replace(/`([^`]+)`/g,(_,v)=>{tokens.push(`<code>${v}</code>`);return `\u0000${tokens.length-1}\u0000`});escaped=escaped.replace(/!\[([^\]]*)\]\(([^)]+)\)/g,(_,label,url)=>{url=safeUrl(url.replaceAll('&amp;','&'),true);return url?`<img src="${escape(url)}" alt="${label}" loading="lazy">`:label});escaped=escaped.replace(/\[([^\]]+)\]\(([^)]+)\)/g,(_,label,url)=>{url=safeUrl(url.replaceAll('&amp;','&'));return url?`<a href="${escape(url)}" target="_blank" rel="noopener noreferrer">${label}</a>`:label});escaped=escaped.replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>');return escaped.replace(/\u0000(\d+)\u0000/g,(_,i)=>tokens[+i])}
function markdown(text){const lines=text.replace(/\r/g,'').split('\n');let html='',code=null,list=null;function close(){if(list){html+=`</${list}>`;list=null}}for(let i=0;i<lines.length;i++){const l=lines[i];if(l.startsWith('```')){close();if(code!==null){html+=`<pre><code>${escape(code.join('\n'))}</code></pre>`;code=null}else code=[];continue}if(code!==null){code.push(l);continue}if(!l.trim()){close();continue}let h=l.match(/^(#{1,6})\s+(.*)/);if(h){close();html+=`<h${h[1].length}>${inline(h[2])}</h${h[1].length}>`;continue}if(/^\s*[-*_]{3,}\s*$/.test(l)){close();html+='<hr>';continue}if(l.includes('|')&&i+1<lines.length&&/^\s*\|?\s*:?-{3,}/.test(lines[i+1])){close();const cells=x=>x.trim().replace(/^\||\|$/g,'').split('|');html+='<table><thead><tr>'+cells(l).map(c=>`<th>${inline(c.trim())}</th>`).join('')+'</tr></thead><tbody>';i++;while(i+1<lines.length&&lines[i+1].includes('|')){i++;html+='<tr>'+cells(lines[i]).map(c=>`<td>${inline(c.trim())}</td>`).join('')+'</tr>'}html+='</tbody></table>';continue}const item=l.match(/^\s*(?:([-*])|(\d+)\.)\s+(.*)/);if(item){let type=item[2]?'ol':'ul';if(list!==type){close();list=type;html+=`<${type}>`}html+=`<li>${inline(item[3])}</li>`;continue}close();if(l.startsWith('>'))html+=`<blockquote>${inline(l.replace(/^>\s?/,''))}</blockquote>`;else html+=`<p>${inline(l)}</p>`}close();if(code!==null)html+=`<pre><code>${escape(code.join('\n'))}</code></pre>`;return html}
const iconPaths={lecture:'M5 4h14v16H5z M8 8h8 M8 12h8 M8 16h5',tutorial:'M8 4v5H3 M16 20v-5h5 M4 9a8 8 0 0 1 14-4 M20 15a8 8 0 0 1-14 4',academic:'M4 19h16 M6 16V9 M12 16V5 M18 16v-5',review:'M9 6h11 M9 12h11 M9 18h11 M3 6h1 M3 12h1 M3 18h1',selftest:'M8 3h8l1 3h3v15H4V6h3z M8 3v4h8V3 M8 13l2 2 5-5'};
const icon=id=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${iconPaths[id]||iconPaths.lecture}"/></svg>`;
const emptyNote=`<div class="note-empty"><div class="empty-document"><svg viewBox="0 0 40 40" aria-hidden="true"><path d="M11 5h13l7 7v23H11z M24 5v9h7 M16 20h10 M16 25h10 M16 30h6"/></svg></div><h2>暂无笔记</h2><p>在左侧输入视频链接，<br>选择模板后点击「生成笔记」。</p></div>`;
function renderTemplates(){$('#templatePicker').innerHTML=state.templates.map(t=>`<button type="button" class="template-card ${t.mode==='selftest'?'study-template':''} ${t.id===state.selected?'selected':''}" data-template="${escape(t.id)}" aria-pressed="${t.id===state.selected}"><span class="template-icon">${icon(t.mode==='selftest'?'selftest':t.id)}</span><span><strong>${escape(t.name)}</strong><small>${escape(t.tag)}</small></span></button>`).join('');$$('[data-template]').forEach(b=>b.onclick=()=>{state.selected=b.dataset.template;renderTemplates()})}
function activeJob(){return state.job&&['queued','running'].includes(state.job.status)}
function setTab(tab){if(tab==='qa'){window.courseQA?.open();return}state.tab=tab;$$('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab);b.setAttribute('aria-selected',b.dataset.tab===tab)});$('#noteContent').hidden=tab!=='note'||state.editing;$('#studyContent').hidden=tab!=='study';$('#transcriptContent').hidden=tab!=='transcript';$('#framesContent').hidden=tab!=='frames';$('#alignedContent').hidden=tab!=='aligned';$('#noteEditor').hidden=!state.editing||tab!=='note';if(tab==='qa')window.courseQA?.load();$('#explainBar').hidden=true}
function renderAligned(j){
 const root=$('#alignedContent');
 if(!j){root.innerHTML='<div class="empty-tab"><h2>图文对照</h2><p>生成一份启用了画面分析的笔记后，章节文字和对应截图会显示在这里。</p></div>';return}
 if(j.analyze_video===false){root.innerHTML='<p class="empty-tab">本次为纯音频模式，没有视频截图可对照。</p>';return}
 const note=$('#noteContent'),frames=(j.frames||[]).filter(f=>safeUrl(f.url,true)).sort((a,b)=>Number(a.time)-Number(b.time));
 if(!j.markdown||!frames.length){root.innerHTML='<p class="empty-tab">需要已生成的笔记和视频截图，才能进行图文对照。</p>';return}
 const temp=document.createElement('div');temp.innerHTML=note.innerHTML;
 const headings=[...temp.querySelectorAll('h2')],chunks=[];
 if(!headings.length){root.innerHTML='<p class="empty-tab">这份笔记没有章节标题，暂时无法按章节对齐。</p>';return}
 headings.forEach((heading,index)=>{
  const nodes=[];for(let node=heading.nextSibling;node&&!(node.nodeType===1&&node.matches('h2'));node=node.nextSibling)nodes.push(node.cloneNode(true));
  const timeLink=heading.querySelector('a[href]');let start=null;
  if(timeLink){try{const u=new URL(timeLink.href,location.href);const value=u.searchParams.get('t');if(value!==null&&Number.isFinite(Number(value)))start=Number(value)}catch{}}
  const title=heading.textContent.trim()||`章节 ${index+1}`;
  chunks.push({index,title,start,nodes});
 });
 let lastStart=0;for(const chunk of chunks){if(chunk.start===null)chunk.start=lastStart;else lastStart=chunk.start}
 chunks.forEach((chunk,index)=>{if(index===0&&chunk.start>0)chunk.start=0;chunk.end=index+1<chunks.length?Math.max(chunk.start,chunks[index+1].start):Infinity});
 const pane=(side)=>chunks.map(chunk=>{
  if(side==='text'){
   const content=chunk.nodes.filter(node=>!(node.nodeType===1&&node.matches('img'))).map(node=>node.outerHTML??escape(node.textContent||'')).join('');
   return `<article class="aligned-section" data-align-index="${chunk.index}"><div class="aligned-section-heading"><span>${String(chunk.index+1).padStart(2,'0')}</span><h2>${escape(chunk.title)}</h2></div><div class="prose aligned-copy">${content||'<p>本章节暂无正文。</p>'}</div></article>`
  }
  const matching=frames.filter(frame=>Number(frame.time)>=chunk.start&&Number(frame.time)<chunk.end);
  if(!matching.length){const nearest=frames.reduce((best,frame)=>Math.abs(Number(frame.time)-chunk.start)<Math.abs(Number(best.time)-chunk.start)?frame:best,frames[0]);matching.push(nearest)}
  return `<section class="aligned-section aligned-image-section" data-align-index="${chunk.index}"><div class="aligned-section-heading"><span>${String(chunk.index+1).padStart(2,'0')}</span><h2>${escape(chunk.title)}</h2></div><div class="aligned-images">${matching.map(frame=>`<figure><img src="${escape(frame.url)}" alt="${escape(chunk.title)} · ${stamp(frame.time)}" loading="lazy"><figcaption><a href="${escape(j.source.url)}&t=${Math.floor(frame.time)}" target="_blank" rel="noopener">${stamp(frame.time)} · 回看 ↗</a></figcaption></figure>`).join('')}</div></section>`
 }).join('');
 root.innerHTML=`<div class="aligned-intro"><strong>图文按章节时间对应</strong><span>滚动任一侧，另一侧会定位到同一章节；无章节时间时按最近截图对应。</span></div><div class="aligned-columns"><div class="aligned-pane aligned-text-pane" aria-label="章节文字"><h3>章节文字</h3>${pane('text')}</div><div class="aligned-pane aligned-frames-pane" aria-label="对应截图"><h3>对应截图</h3>${pane('image')}</div></div>`;
 const panes=[...root.querySelectorAll('.aligned-pane')];let active=-1,activePane=null,frame=0;
 const sync=(source,target)=>{if(activePane!==source)return;const bounds=source.getBoundingClientRect(),header=source.querySelector(':scope > h3'),threshold=bounds.top+(header?.getBoundingClientRect().height||0)+12,sections=[...source.querySelectorAll('[data-align-index]')];const current=sections.find(section=>section.getBoundingClientRect().bottom>threshold)||sections.at(-1);if(!current)return;const index=Number(current.dataset.alignIndex);if(index===active)return;active=index;panes.forEach(p=>p.querySelectorAll('[data-align-index]').forEach(item=>item.classList.toggle('is-current',Number(item.dataset.alignIndex)===index)));const counterpart=target.querySelector(`[data-align-index="${index}"]`);if(!counterpart)return;const targetRect=target.getBoundingClientRect(),sticky=target.querySelector(':scope > h3'),offset=(sticky?.getBoundingClientRect().height||0)+12;const next=Math.max(0,Math.min(target.scrollHeight-target.clientHeight,target.scrollTop+counterpart.getBoundingClientRect().top-targetRect.top-offset));if(Math.abs(next-target.scrollTop)>2)target.scrollTop=next};
 panes.forEach((pane,index)=>{const claim=()=>{activePane=pane};pane.addEventListener('wheel',claim,{passive:true});pane.addEventListener('touchstart',claim,{passive:true});pane.addEventListener('pointerdown',claim,{passive:true});pane.addEventListener('keydown',event=>{if(['ArrowDown','ArrowUp','PageDown','PageUp','Home','End',' '].includes(event.key))claim()});pane.addEventListener('scroll',()=>{if(activePane&&activePane!==pane)return;if(!activePane)activePane=pane;if(frame)return;frame=requestAnimationFrame(()=>{frame=0;sync(pane,panes[1-index])})},{passive:true})});
}
// Group only for reading; original transcript timestamps remain available for retrieval.
function transcriptParagraphs(segments){
 const result=[];let group=null;
 for(const segment of segments||[]){
  const text=String(segment.text||'').trim();if(!text)continue;
  const start=Number(segment.start)||0,end=Math.max(start,Number(segment.end)||start);
  if(group){
   const span=group.end-group.start;
   const sentenceEnd=/[。！？.!?][”’"']?$/.test(group.text);
   if(start-group.end>=3 || (span>=25&&sentenceEnd) || span>=65 || group.text.length>=420){result.push(group);group=null;}
  }
  if(!group)group={start,end,text};
  else{group.text+=' '+text;group.end=Math.max(group.end,end);}
 }
 if(group)result.push(group);return result;
}
function renderJob(){const j=state.job;window.bijiScene?.setBusy(!!activeJob());if(state.tab==='qa'&&(!j||j.status!=='done'))state.tab='aligned';window.courseQA?.setJob(j);$('[data-tab=qa]').disabled=!j||j.status!=='done';$('#openRetrieval').hidden=!j||j.status!=='done';if(!j){$('#noteContent').innerHTML=emptyNote;$('#noteBadge').hidden=true;$('#editNote').hidden=true;$('#exportNote').hidden=true;$('#generateStudy').hidden=true;$('[data-tab=study]').hidden=true;$('#transcriptContent').innerHTML='<p class="empty-tab">暂无转写文本。</p>';$('#framesContent').innerHTML='<p class="empty-tab">暂无视频截图。</p>';renderAligned(null);setTab(state.tab);return}$('#noteBadge').hidden=false;$('#noteBadge').textContent={queued:'排队中',running:'生成中',done:j.template.name,error:'待重试',cancelled:'已停止'}[j.status]||j.status;$('#jobProgress').hidden=!activeJob();$('#progressLabel').textContent=j.stage;$('#progressBar').value=j.progress;$('#progressDetail').textContent=`${j.progress}% · 已完成的步骤会自动保留`;
$('#jobError').hidden=!['error','cancelled'].includes(j.status);$('#jobError').textContent=j.error||j.stage;if(!$('#jobError').hidden){const b=document.createElement('button');b.textContent='继续处理';b.onclick=()=>retry(false);$('#jobError').append(b);const fresh=document.createElement('button');fresh.textContent='重新分析视频';fresh.onclick=()=>retry(true);$('#jobError').append(fresh)}
if(!state.editing)$('#noteContent').innerHTML=j.template?.mode==='selftest'?`<div class="empty-tab"><h2>旧版自测记录</h2><p>这条记录生成于“自测”仍作为首次生成模板的旧版本。点击下方「重新生成笔记」，先生成课程笔记，再按需生成知识点自测。</p></div>`:j.markdown?markdown(j.markdown):`<div class="empty-tab"><h2>${escape(j.title)}</h2><p>${activeJob()?'正在整理课程笔记。你可以离开页面，任务会在后台继续。':'还没有生成笔记。已处理的材料可在其他标签查看。'}</p></div>`;
const tr=j.transcript;$('#transcriptContent').innerHTML=tr?`<div class="transcript-source">${escape(tr.source)}${tr.precision==='chunk'?' · 服务未提供逐句时间戳，以下为音频分块时间范围':''}<br>原始识别结果，未经人工校对。</div>`+transcriptParagraphs(tr.segments).map(s=>`<div class="transcript-row"><a href="${escape(j.source.url)}&t=${Math.floor(s.start)}" target="_blank" rel="noopener">${stamp(s.start)}–${stamp(s.end)}</a><p>${escape(s.text)}</p></div>`).join(''):'<p class="empty-tab">暂无转写内容。</p>';
$('#framesContent').innerHTML=j.frames?.length?j.frames.map(f=>`<figure class="frame-card"><img src="${escape(f.url)}" alt="课程画面 ${stamp(f.time)}" loading="lazy"><figcaption><a href="${escape(j.source.url)}&t=${Math.floor(f.time)}" target="_blank" rel="noopener">${stamp(f.time)} · 回看这一刻 ↗</a></figcaption></figure>`).join(''):`<p class="empty-tab">${j.analyze_video===false?'本次未启用画面分析，仅使用字幕或语音。':'暂无关键画面。'}</p>`;renderAligned(j);
if(!state.editing)renderStudy();$('#editNote').hidden=!j.markdown||j.template?.mode==='selftest';$('#exportNote').hidden=!j.markdown;$('#generateStudy').hidden=!j.markdown||j.status!=='done'||j.template?.mode==='selftest';$('#generateStudy').textContent=j.quiz?'重新生成自测':j.quiz_status==='error'?'重试自测':'生成自测';$('#generateStudy').disabled=j.quiz_status==='running';$('[data-tab=study]').hidden=!j.quiz&&j.quiz_status!=='running'&&j.quiz_status!=='error';$('#provenance').hidden=!j.models_used;$('#usedModels').innerHTML=modelRows(j.models_used||{});$('[data-tab=note]').textContent='笔记';$('#sourceLabel').textContent=`${j.source.bvid} · P${j.source.part} · ${j.analyze_video===false?'纯音频模式':(j.frames?.length||0)+' 张画面'}`;
$('#editNote').disabled=!j.markdown||activeJob();$('#exportNote').disabled=!j.markdown||state.editing;$('#regenerate').hidden=!j.markdown||!!activeJob();$('#createButton').disabled=false;setTab(state.tab)}
async function loadHistory(){const list=await api('/api/jobs');$('#navCount').textContent=list.length;$('#historyCount').textContent=`${list.length} 份笔记`;$('#historyList').innerHTML=list.length?list.map(j=>`<button class="history-card" data-job="${j.id}"><div class="history-card-top"><span>${escape(j.template.name)}</span><span>${new Date(j.created_at*1000).toLocaleDateString('zh-CN')}</span></div><h3>${escape(j.title)}</h3><div class="history-card-bottom"><span>${{queued:'等待处理',running:'正在生成',done:'已完成',error:'需要重试',cancelled:'已停止'}[j.status]} · P${j.source.part}</span><span>↗</span></div></button>`).join(''):'<div class="history-empty"><div class="empty-icon">▤</div><div><strong>暂无记录</strong></div></div>';$$('[data-job]').forEach(b=>b.onclick=async()=>{if(state.editing&&!confirm('放弃当前未保存的编辑？'))return;if(!await flushStudy())return;state.editing=false;$('#editNote').textContent='编辑';await openJob(b.dataset.job);$('#workspace').scrollIntoView({behavior:'smooth'})});return list}
async function openJob(id){const switching=state.job?.id!==id;state.job=await api('/api/jobs/'+id);if(switching){state.tab='aligned';clearTimeout(state.studyPoll);$('#analyzeVideo').checked=state.job.analyze_video!==false;updateVideoMode()}state.selected=state.job.template?.mode==='selftest'?(state.templates.find(t=>t.mode!=='selftest')?.id||'lecture'):state.job.template.id;$('#instructions').value=state.job.instructions||'';renderTemplates();renderJob();clearTimeout(state.poll);if(activeJob())state.poll=setTimeout(poll,2000);if(state.job.quiz_status==='running'&&!state.studyPoll)state.studyPoll=setTimeout(pollStudy,1200)}
async function poll(){try{await openJob(state.job.id);await loadHistory()}catch(e){toast(e.message);state.poll=setTimeout(poll,5000)}}
async function pollStudy(){try{const job=await api('/api/jobs/'+state.job.id);state.job=job;if(job.quiz_status==='running'){state.studyPoll=setTimeout(pollStudy,1800);return}renderJob();if(job.quiz_status==='done')toast('知识点自测已生成');else if(job.quiz_status==='error')toast(job.quiz_error||'自测生成失败')}catch(e){toast(e.message)}}
async function retry(refresh){if(refresh&&!confirm('重新分析会清除已有转写与画面分析缓存，并重新调用模型，可能产生费用。继续？'))return;try{state.job=await api(`/api/jobs/${state.job.id}/retry`,{method:'POST',body:JSON.stringify({refresh_analysis:refresh,analyze_video:$('#analyzeVideo').checked})});renderJob();state.poll=setTimeout(poll,1000);loadHistory()}catch(e){toast(e.message)}}
function updateVideoMode(){$('#videoModeHint').textContent=$('#analyzeVideo').checked?'结合字幕或语音与截图生成笔记':'仅字幕或语音，不截图、不调用视觉模型'}
$('#analyzeVideo').onchange=()=>{updateVideoMode();health().catch(()=>{})};
$('#createForm').onsubmit=async e=>{e.preventDefault();const b=$('#createButton');if(!await flushStudy())return;b.disabled=true;try{const j=await api('/api/jobs',{method:'POST',body:JSON.stringify({text:$('#videoLink').value,template_id:state.selected,instructions:$('#instructions').value,analyze_video:$('#analyzeVideo').checked})});state.editing=false;$('#editNote').textContent='编辑';setTab('aligned');await openJob(j.id);await loadHistory();toast('已加入处理队列')}catch(e){toast(e.message)}finally{b.disabled=false}};
$('#resolveLink').onclick=async()=>{const b=$('#resolveLink');b.disabled=true;$('#linkResult').textContent='正在解析…';try{let r=await api('/api/resolve',{method:'POST',body:JSON.stringify({text:$('#videoLink').value})});$('#linkResult').className='inline-result';$('#linkResult').textContent=`已识别 ${r.bvid} · 第 ${r.part} P`;}catch(e){$('#linkResult').className='inline-result error';$('#linkResult').textContent=e.message}finally{b.disabled=false}};
$('#clearLink').onclick=()=>{$('#videoLink').value='';$('#linkResult').textContent='';$('#videoLink').focus()};$$('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
function updateFullscreenButton(){const active=document.body.classList.contains('focus-reading');$('#focusMode').setAttribute('aria-pressed',String(active));$('#focusMode').textContent=active?'退出全屏 ×':'全屏 ⛶'}
$('#focusMode').onclick=async()=>{const on=!document.body.classList.contains('focus-reading');document.body.classList.toggle('focus-reading',on);updateFullscreenButton();if(on){try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen()}catch{}}else if(document.fullscreenElement){try{await document.exitFullscreen()}catch{}}};
document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement&&document.body.classList.contains('focus-reading'))document.body.classList.remove('focus-reading');updateFullscreenButton()});
$('#generateStudy').onclick=async()=>{if(state.job?.quiz&&!confirm('重新生成会替换当前题目并清除这份自测的作答记录，继续吗？'))return;if(!await flushStudy())return;try{clearTimeout(state.studyPoll);state.tab='study';state.job.quiz=null;state.job.quiz_status='running';state.job.quiz_error=null;renderJob();await api(`/api/jobs/${state.job.id}/study/generate`,{method:'POST'});state.studyPoll=setTimeout(pollStudy,1200)}catch(e){state.job.quiz_status='error';state.job.quiz_error=e.message;renderJob();toast(e.message)}};$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());
$('#cancelJob').onclick=async()=>{try{await api(`/api/jobs/${state.job.id}/cancel`,{method:'POST'});toast('已请求停止，当前请求结束后生效')}catch(e){toast(e.message)}};
$('#regenerate').onclick=async()=>{if(!await flushStudy())return;if(!confirm('使用左侧当前模板重新生成笔记？会调用笔记模型，原笔记会保存到本地版本目录。'))return;try{state.job=await api(`/api/jobs/${state.job.id}/retry`,{method:'POST',body:JSON.stringify({template_id:state.selected,instructions:$('#instructions').value,analyze_video:$('#analyzeVideo').checked})});renderJob();state.poll=setTimeout(poll,1000)}catch(e){toast(e.message)}};
$('#editNote').onclick=async()=>{if(!state.editing){state.editing=true;$('#noteEditor').value=state.job.markdown;$('#editNote').textContent='保存';setTab('note');$('#noteEditor').focus();$('#exportNote').disabled=true}else{try{state.job=await api(`/api/jobs/${state.job.id}/note`,{method:'PUT',body:JSON.stringify({markdown:$('#noteEditor').value})});state.editing=false;$('#editNote').textContent='编辑';renderJob();toast('笔记已保存')}catch(e){toast(e.message)}}};
$('#exportNote').onclick=async()=>{if(await flushStudy())$('#exportDialog').showModal()};$('#downloadZip').onclick=()=>{const a=document.createElement('a');a.href=`/api/jobs/${state.job.id}/export`;a.download='课程笔记.zip';a.click();$('#exportDialog').close()};$('#printPdf').onclick=async()=>{$('#exportDialog').close();setTab('note');const imgs=$$('#noteContent img');await Promise.all(imgs.map(im=>{im.loading='eager';return im.decode().catch(()=>{})}));window.print()};
function providerFields(cfg){$('#providerFields').innerHTML=[['text','笔记生成','文字模型'],['vision','画面理解','必须支持图片输入'],['asr','语音转写','无字幕时使用']].map(([k,name,desc])=>`<section class="provider-section"><h3>${name}<span>${desc}</span>${k==='vision'?'<button type="button" id="copyProvider">复用笔记服务</button>':''}</h3><label>API 基础地址<input id="${k}Url" value="${escape(cfg[k].base_url)}" placeholder="https://你的服务商/v1" type="url"></label><div class="two-fields"><label>模型名称<input id="${k}Model" value="${escape(cfg[k].model)}" placeholder="服务商提供的模型 ID"></label><label>API Key<input id="${k}Key" type="password" autocomplete="new-password" placeholder="${cfg[k].has_key?'已保存，留空保持不变':'输入 API Key'}"></label></div><label class="check-label"><input id="${k}Clear" type="checkbox">清除已保存的密钥</label></section>`).join('');$('#copyProvider').onclick=()=>{$('#visionUrl').value=$('#textUrl').value;$('#visionModel').value=$('#textModel').value;$('#visionKey').value=$('#textKey').value;toast('已复制可见配置；已保存的密钥不会回显，请为画面服务单独填写密钥')}}
$('#openSettings').onclick=async()=>{try{const cfg=await api('/api/settings');providerFields(cfg);$('#preferSubtitles').checked=cfg.prefer_subtitles;$('#frameInterval').value=cfg.frame_interval;$('#maxFrames').value=cfg.max_frames;$('#glossary').value=cfg.glossary;$('#biliCookie').value='';$('#biliCookie').placeholder=cfg.has_cookie?'已保存，留空保持不变':'仅保存在当前部署，不发送给模型服务';$('#clearCookie').checked=false;$('#settingsStatus').textContent='';$('#settingsDialog').showModal()}catch(e){toast(e.message)}};
function setupAsr(cfg){
 const section=$('#asrUrl').closest('.provider-section');
 section.insertAdjacentHTML('afterbegin',`<label>语音服务<select id="asrProvider"><option value="openai">通用转写（OpenAI 兼容）</option><option value="doubao">豆包录音识别 2.0</option></select></label><div id="doubaoOptions" hidden><label>认证方式<select id="asrAuth"><option value="api_key">豆包语音 API Key（新版控制台）</option><option value="app_token">APP ID + Access Token（旧版控制台）</option></select></label><label id="asrAppLabel">APP ID<input id="asrAppId" autocomplete="off"></label><p>接口地址与模型已自动配置。凭证请从<a href="https://console.volcengine.com/speech/new/" target="_blank" rel="noopener">豆包语音控制台</a>获取，不是方舟模型的 API Key。</p></div>`);
 $('#asrProvider').value=cfg.asr.provider||'openai';$('#asrAuth').value=cfg.asr.auth_mode||'api_key';$('#asrAppId').value=cfg.asr.app_id||'';
 const update=()=>{const d=$('#asrProvider').value==='doubao';$('#doubaoOptions').hidden=!d;$('#asrUrl').parentElement.hidden=d;$('#asrModel').parentElement.hidden=d;$('#asrUrl').required=false;$('#asrModel').required=false;$('#asrAppLabel').hidden=$('#asrAuth').value!=='app_token';$('#asrKey').parentElement.firstChild.textContent=d&&$('#asrAuth').value==='app_token'?'Access Token':'API Key';};
 const changed=()=>{$('#asrKey').value='';$('#asrKey').placeholder='请填写所选服务对应的凭证';update()};
 $('#asrProvider').onchange=changed;$('#asrAuth').onchange=changed;update();
}
const originalProviderFields=providerFields;providerFields=function(cfg){originalProviderFields(cfg);setupAsr(cfg)};
$('#settingsForm').onsubmit=async e=>{e.preventDefault();let cfg={};for(const k of ['text','vision','asr'])cfg[k]={base_url:$('#'+k+'Url').value,model:$('#'+k+'Model').value,api_key:$('#'+k+'Key').value,clear_key:$('#'+k+'Clear').checked};Object.assign(cfg.asr,{provider:$('#asrProvider').value,auth_mode:$('#asrAuth').value,app_id:$('#asrAppId').value});Object.assign(cfg,{prefer_subtitles:$('#preferSubtitles').checked,frame_interval:Number($('#frameInterval').value),max_frames:Number($('#maxFrames').value),glossary:$('#glossary').value,cookie:$('#biliCookie').value,clear_cookie:$('#clearCookie').checked});try{await api('/api/settings',{method:'PUT',body:JSON.stringify(cfg)});$('#settingsDialog').close();toast('设置已保存');await health()}catch(e){$('#settingsStatus').textContent=e.message}};
function modelRows(models){return [['text','笔记生成'],['vision','画面理解'],['asr','语音转写']].map(([k,label])=>`<div class="model-row"><span>${label}</span><strong>${escape(models[k]||'未记录')}</strong></div>`).join('')}
async function health(){const [h,cfg]=await Promise.all([api('/api/health'),api('/api/settings')]);$('#currentModel').textContent=cfg.text.model||'未配置模型';$('#currentModel').title=cfg.text.model||'未配置模型';const ready=!!(cfg.text.base_url&&cfg.text.model&&(!$('#analyzeVideo').checked||(cfg.vision.base_url&&cfg.vision.model)));$('.model-indicator').classList.toggle('ready',ready);$('#modelList').innerHTML=modelRows(Object.fromEntries(['text','vision','asr'].map(k=>[k,cfg[k].model||'未配置'])));$('#connectionNote').innerHTML=ready?(h.ffmpeg&&h.ffprobe?'模型已配置':'缺少 FFmpeg，请先安装媒体处理工具'):'请先在<button id="setupLink">模型与配置</button>中配置 API';if($('#setupLink'))$('#setupLink').onclick=()=>$('#openSettings').click()}
function templateEditor(id){state.templateEdit=id;const t=state.templates.find(x=>x.id===id);$('#templateList').innerHTML=state.templates.map(t=>`<button class="${id===t.id?'selected':''}" data-edit-template="${escape(t.id)}">${escape(t.name)}</button>`).join('');$$('[data-edit-template]').forEach(b=>b.onclick=()=>templateEditor(b.dataset.editTemplate));$('#templateName').value=t?.name||'';$('#templateTag').value=t?.tag||'';$('#templatePrompt').value=t?.prompt||'';$('#templateMode').value=t?.mode||'note';$('#deleteTemplate').hidden=!t}
$('#openTemplates').onclick=()=>{templateEditor(state.selected);$('#templatesDialog').showModal()};$('#addTemplate').onclick=()=>templateEditor('custom-'+Date.now());
$('#templateForm').onsubmit=async e=>{e.preventDefault();const t={id:state.templateEdit,name:$('#templateName').value,tag:$('#templateTag').value,prompt:$('#templatePrompt').value,mode:$('#templateMode').value};const list=state.templates.filter(x=>x.id!==t.id);const index=state.templates.findIndex(x=>x.id===t.id);list.splice(index<0?list.length:index,0,t);try{state.templates=await api('/api/templates',{method:'PUT',body:JSON.stringify(list)});state.selected=t.id;renderTemplates();templateEditor(t.id);toast('模板已保存')}catch(e){toast(e.message)}};
$('#deleteTemplate').onclick=async()=>{if(state.templates.length<=1){toast('至少保留一个模板');return}if(!confirm('删除这个笔记模板？已有笔记不受影响。'))return;try{state.templates=await api('/api/templates',{method:'PUT',body:JSON.stringify(state.templates.filter(t=>t.id!==state.templateEdit))});state.selected=state.templates[0].id;renderTemplates();templateEditor(state.selected)}catch(e){toast(e.message)}};
$('#authForm').onsubmit=async e=>{e.preventDefault();try{const r=await fetch('/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:$('#accessToken').value})});if(!r.ok)throw Error('访问口令不正确');$('#accessToken').value='';$('#authDialog').close();await init()}catch(e){$('#authError').textContent=e.message}};
window.addEventListener('beforeunload',e=>{if(state.editing||studyDirty.size){e.preventDefault();e.returnValue=''}});
const studyTimers=new Map(),studyPending=new Map(),studyDirty=new Set();
function renderStudy(){
 const j=state.job,qz=j.quiz;if(!qz){$('#studyContent').innerHTML=j.quiz_status==='running'?'<div class="empty-tab"><h2>正在生成自测</h2><p>正在依据整理后的笔记提取知识点并编写题目，不会重新分析视频。</p></div>':j.quiz_status==='error'?`<div class="empty-tab"><h2>自测生成失败</h2><p>${escape(j.quiz_error||'请重试。')}</p><button class="secondary-button" id="retryStudy">重试生成自测</button></div>`:'';if($('#retryStudy'))$('#retryStudy').onclick=()=>$('#generateStudy').click();return}
 const responses=qz.responses||{};const mastered=Object.values(responses).filter(r=>r.mastery==='mastered').length;
 $('#studyContent').innerHTML=`<div class="study-header"><h1>知识点自测</h1><p>题目依据已整理完成的笔记生成，先独立作答，再查看答案与解释。</p></div><div class="study-summary"><span id="studySummary">${qz.questions.length} 道题 · 已掌握 ${mastered} 道</span><button class="text-button" id="resetStudy">重新自测</button></div>`+qz.questions.map((q,i)=>{
 const r=responses[q.id]||{};return `<section class="question-card" data-question="${q.id}"><div class="question-meta"><span class="question-number">${String(i+1).padStart(2,'0')} / ${String(qz.questions.length).padStart(2,'0')}</span><span>${escape(q.knowledge_point||'知识点自测')}</span></div><h2>${escape(q.question)}</h2><label for="answer-${q.id}">你的回答</label><textarea id="answer-${q.id}" class="question-input" placeholder="写下你的理解…" rows="3" maxlength="12000">${escape(r.answer||'')}</textarea><div class="question-actions"><button class="reveal-button">${r.revealed?'收起答案':'查看答案'}</button><button class="skip-button">暂时不会</button><span class="save-status" role="status">${r.saved_at?'已保存':''}</span></div><div class="answer-panel" ${r.revealed?'':'hidden'}><h3>参考答案</h3><p>${escape(q.answer)}</p>${q.explanation?`<p>${escape(q.explanation)}</p>`:''}<div class="evidence">知识依据：${escape(q.evidence)}</div><div class="mastery-controls"><button data-mastery="mastered" class="${r.mastery==='mastered'?'active':''}">已掌握</button><button data-mastery="review" class="${r.mastery==='review'?'active':''}">需要复习</button></div></div></section>`}).join('');
 $$('.question-card').forEach(card=>{
  card.querySelector('textarea').addEventListener('input',()=>{const key=j.id+':'+card.dataset.question;studyDirty.add(key);card.querySelector('.save-status').textContent='未保存';clearTimeout(studyTimers.get(key));studyTimers.set(key,setTimeout(()=>{studyTimers.delete(key);persistQuestion(card).catch(()=>{})},700))});
  card.querySelector('.reveal-button').onclick=async()=>{try{const show=card.querySelector('.answer-panel').hidden;await persistQuestion(card,{revealed:show});card.querySelector('.answer-panel').hidden=!show;card.querySelector('.reveal-button').textContent=show?'收起答案':'查看答案'}catch{}};
  card.querySelector('.skip-button').onclick=async()=>{try{await persistQuestion(card,{revealed:true,mastery:'review'});card.querySelector('.answer-panel').hidden=false;card.querySelector('.reveal-button').textContent='收起答案';syncMastery(card,'review')}catch{}};
  card.querySelectorAll('[data-mastery]').forEach(b=>b.onclick=async()=>{try{await persistQuestion(card,{mastery:b.dataset.mastery});syncMastery(card,b.dataset.mastery)}catch{}});
 });
 $('#resetStudy').onclick=async()=>{if(!confirm('清空这份自测的作答和掌握状态，重新开始？不会重新调用模型。'))return;if(!await flushStudy())return;try{for(const card of $$('.question-card')){card.querySelector('textarea').value='';await persistQuestion(card,{answer:'',revealed:false,mastery:'unmarked'})}renderStudy()}catch{}};
}
function syncMastery(card,value){card.querySelectorAll('[data-mastery]').forEach(b=>b.classList.toggle('active',b.dataset.mastery===value));const n=Object.values(state.job.quiz.responses||{}).filter(r=>r.mastery==='mastered').length;$('#studySummary').textContent=`${state.job.quiz.questions.length} 道题 · 已掌握 ${n} 道`}
function persistQuestion(card,change={}){
 const job=state.job,quiz=job.quiz,qid=card.dataset.question,key=job.id+':'+qid;clearTimeout(studyTimers.get(key));studyTimers.delete(key);
 const old=quiz.responses?.[qid]||{};const payload={version:quiz.version,answer:card.querySelector('textarea').value,revealed:old.revealed||false,mastery:old.mastery||'unmarked',...change};
 quiz.responses||={};quiz.responses[qid]={...old,...payload};studyDirty.add(key);card.querySelector('.save-status').textContent='保存中…';
 const task=(studyPending.get(key)||Promise.resolve()).catch(()=>{}).then(()=>api(`/api/jobs/${job.id}/study/${qid}`,{method:'PUT',body:JSON.stringify(payload)})).then(result=>{if(studyPending.get(key)===task&&card.querySelector('textarea').value===payload.answer){quiz.responses[qid]=result;studyDirty.delete(key);card.querySelector('.save-status').textContent='已保存'}return result}).catch(e=>{card.querySelector('.save-status').textContent='保存失败';toast(e.message);throw e}).finally(()=>{if(studyPending.get(key)===task)studyPending.delete(key)});
 studyPending.set(key,task);return task;
}
async function flushStudy(){try{for(const card of $$('.question-card')){const key=state.job.id+':'+card.dataset.question;if(studyTimers.has(key)||studyDirty.has(key)&&!studyPending.has(key))persistQuestion(card).catch(()=>{})}await Promise.all([...studyPending.values()]);return !studyDirty.size}catch{return false}}
let sceneTick=false;
function updateScene(){sceneTick=false;if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;document.documentElement.style.setProperty('--scene-y',Math.min(65,scrollY*.085)+'px')}
window.addEventListener('scroll',()=>{if(!sceneTick){sceneTick=true;requestAnimationFrame(updateScene)}},{passive:true});
const sectionObserver=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){$$('.topbar nav a').forEach(a=>a.classList.toggle('nav-active',a.getAttribute('href')==='#'+entry.target.id))}},{rootMargin:'-15% 0px -50% 0px'});['workspace','history'].forEach(id=>sectionObserver.observe($('#'+id)));
async function init(){try{state.templates=await api('/api/templates');state.selected=state.templates[0].id;renderTemplates();await health();const list=await loadHistory();const running=list.find(j=>['running','queued'].includes(j.status));if(running)await openJob(running.id);else renderJob()}catch(e){toast(e.message)}}
renderJob();init();
$$('[data-tab]').forEach(button=>button.addEventListener('keydown',event=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();const tabs=$$('[data-tab]').filter(t=>!t.disabled&&!t.hidden);const current=tabs.indexOf(button);const next=event.key==='Home'?0:event.key==='End'?tabs.length-1:(current+(event.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[next].focus();setTab(tabs[next].dataset.tab)}}));
